### ISSUE TITLE
linter.jl: special rule for ordering of SU items is not respected

### ISSUE THREAD

**Issue by vaitkus** [jamesrhester/julia_cif_tools#6]
Rule 4.1.10 of the Style Guide for DDLm Dictionaries states that:
```
Notwithstanding (8), SU definitions always follow the definitions
of their corresponding Measurand data names.
```
However, it seems that this rule is not respected by `linter.jl`. For example, definition of the `_chemical.melting_point_su` data item from the `CIF_CORE` [1] dictionary is currently placed after `_chemical.melting_point_lt` and does not trigger any warning messages. What is more, moving this definition immediately after the related Measurand definition (`_chemical.melting_point`) results in warning messages complaining about the incorrect order of category items.

The same rule is also not respected by `pretty_print.jl`.

[1] https://github.com/COMCIFS/cif_core/blob/5a14e20e7b09d83e0ef6183c81f8154f2b3fd075/cif_core.dic#L8540

**Comment by jamesrhester** [comment]
Thanks for the report. This is fixed by commit ebaed5. It was due to the linter not introspecting into import attributes, and therefore missing the SU `_type.purpose`. `pretty_print.jl` has also been fixed via a fix to the underlying package `CrystalInfoFramework.jl`, which also did not introspect into import attributes.

**Comment by vaitkus** [comment]
Great, thank you for the changes. However, I ran into a few issues while trying to run the updated version of the `linter.jl`:
1) The import logic seems to incorrectly treat save frame codes as case sensitive which leads to it not being able to handle certain files. For example, the linter fails to import the `colour_rgb` save frame in `CIF_CORE` since it the save frame is named `colour_RGB` in the `templ_enum.cif` file.
2) Current implementation assumes that the imported files reside in the same directory as the importing file. While his is true for the `cif_core` repository, dictionaries like the `TopoCif` rely on files from other repositories/directories. It would be useful to have an command line option or an environment variable which would allow to specify a search path for the imported files.

**Comment by jamesrhester** [comment]
1. `CrystalInfoFramework.jl` has to updated to the latest version in order for `linter.jl` to properly handle save frame case-insensitivity (which was a bug)
2. Good suggestion. Ideally a full URI for the imported file is given in the import attribute but until we have them in permanent position a command-line option makes sense.

**Comment by vaitkus** [comment]
> * `CrystalInfoFramework.jl` has to updated to the latest version in order for `linter.jl` to properly handle save frame case-insensitivity (which was due to a bug in `CrystalInfoFramework.jl`)

Thank you for the hint, that was my oversight. Now everything works as expected.

> * Good suggestion. Ideally a full URI for the imported file is given in the import attribute but until we have them in permanent position a command-line option makes sense.

Great that you also see some value in that. I opened a separate issue for this topic (#7).
