### ISSUE TITLE
linter.jl: add means to specify the search path of imported files

### ISSUE THREAD

**Issue by vaitkus** [jamesrhester/julia_cif_tools#7]
This issue is based on the short discussion that took place in the comments of issue #6.

Current implementation of `linter.jl` assumes that the imported files reside in the same directory as the importing file. While this is true for the `cif_core` repository [1], other usage scenarios may require a more flexible approach. For example, automated checks in the `TopoCif` [2] repository (that rely on tools from this repository) currently complain about missing imported files while checking the `Topology.dic` dictionary, even though the required files are actually present on the system during the testing, just not in the same directory as the `Topology.dic` dictionary.

Ideally, the dictionary import statements should provide full URIs of the imported files, however, until dictionary files are placed in permanent locations, a command-line option which allows to specify a local system search path for the imported files would be useful.

[1] https://github.com/COMCIFS/cif_core
[2] https://github.com/COMCIFS/TopoCif

**Comment by jamesrhester** [comment]
The current version includes option `-i` to specify a local file location.
